import { useEffect, useMemo, useState } from "react";
import { supabase } from "../lib/supabaseClient";
import { useAuth } from "../lib/AuthContext";
import { openPrintDocument, formatDate, infoGrid, section, kpis, table } from "../lib/printDocument";

const TABS = [
  ["desempenho", "Desempenho"], ["360", "Avaliação 360°"], ["comportamental", "Comportamental"],
  ["experiencia", "Experiência"], ["competencias", "Competências"], ["metas", "Metas"],
  ["feedbacks", "Feedbacks"], ["pdi", "PDI"], ["ninebox", "Nine Box"], ["historico", "Histórico"],
];
const TYPE_LABEL = { gestor: "Gestor", autoavaliacao: "Autoavaliação", pares: "Pares", subordinados: "Subordinados" };
const DISC = [["dominance", "D", "Dominância"], ["influence", "I", "Influência"], ["steadiness", "S", "Estabilidade"], ["compliance", "C", "Conformidade"]];

function polar(cx, cy, radius, angle) { const a = angle - Math.PI / 2; return [cx + radius * Math.cos(a), cy + radius * Math.sin(a)]; }
function polygonPoints(values, max = 10, size = 250, radius = 82) {
  return values.map((v, i) => polar(size / 2, size / 2, Math.max(0, Math.min(max, Number(v || 0))) / max * radius, i * Math.PI * 2 / values.length)).join(" ");
}
function RadarChart({ items = [], max = 10, title = "Perfil" }) {
  const safe = items.filter(x => Number.isFinite(Number(x.value)));
  if (safe.length < 3) return <div className="chart-empty">Dados insuficientes para o gráfico.</div>;
  const size = 250, cx = size / 2, cy = size / 2, radius = 82;
  return <div className="chart-card"><div className="chart-title-row"><strong>{title}</strong><span>Escala 0–{max}</span></div><div className="radar-wrap"><svg viewBox={`0 0 ${size} ${size}`} role="img" aria-label={title}>
    {[25,50,75,100].map(l => <polygon key={l} points={polygonPoints(safe.map(() => l),100,size,radius)} fill="none" className="radar-grid"/>)}
    {safe.map((x,i)=>{const [x1,y1]=polar(cx,cy,radius+20,i*Math.PI*2/safe.length);const [x2,y2]=polar(cx,cy,radius,i*Math.PI*2/safe.length);return <g key={x.name+i}><line x1={cx} y1={cy} x2={x2} y2={y2} className="radar-axis"/><text x={x1} y={y1} textAnchor="middle" className="radar-label">{String(x.name).slice(0,15)}</text></g>;})}
    <polygon points={polygonPoints(safe.map(x=>x.value),max,size,radius)} className="radar-area"/>
    {safe.map((x,i)=>{const [px,py]=polar(cx,cy,Math.max(0,Math.min(max,Number(x.value)))/max*radius,i*Math.PI*2/safe.length);return <circle key={i} cx={px} cy={py} r="4" className="radar-dot"/>;})}
  </svg></div></div>;
}
function DonutChart({ items = [], title = "Distribuição" }) {
  const safe=items.filter(x=>Number(x.value)>0), total=safe.reduce((s,x)=>s+Number(x.value),0); if(!total)return <div className="chart-empty">Ainda não existem dados para este gráfico.</div>;
  let offset=0; const r=48,c=2*Math.PI*r; const palette=["#2563EB","#2F9E68","#D97706","#7C3AED","#C9483D","#0891B2"];
  return <div className="chart-card"><div className="chart-title-row"><strong>{title}</strong><span>{total} registro(s)</span></div><div className="donut-layout"><svg viewBox="0 0 120 120" className="donut-svg"><circle cx="60" cy="60" r={r} fill="none" stroke="var(--line)" strokeWidth="16"/>{safe.map((x,i)=>{const len=Number(x.value)/total*c;const el=<circle key={i} cx="60" cy="60" r={r} fill="none" stroke={palette[i%palette.length]} strokeWidth="16" strokeDasharray={`${len} ${c-len}`} strokeDashoffset={-offset} transform="rotate(-90 60 60)"/>;offset+=len;return el;})}<text x="60" y="57" textAnchor="middle" className="donut-total">{total}</text><text x="60" y="70" textAnchor="middle" className="donut-sub">registros</text></svg><div className="chart-legend">{safe.map((x,i)=><div key={i}><i style={{background:palette[i%palette.length]}}/><span>{x.label}</span><b>{Number(x.value)}</b></div>)}</div></div></div>;
}
function GoalRings({goals=[]}) { if(!goals.length)return <div className="chart-empty">Nenhuma meta cadastrada para o colaborador.</div>; return <div className="rings-grid">{goals.map((g,i)=>{const cur=Number(g.current_value||0),target=Number(g.target_value||0),pct=target>0?Math.max(0,Math.min(100,cur/target*100)):0,r=28,c=2*Math.PI*r;return <div className="ring-card" key={g.id||i}><svg viewBox="0 0 70 70"><circle cx="35" cy="35" r={r} fill="none" stroke="var(--line)" strokeWidth="7"/><circle cx="35" cy="35" r={r} fill="none" stroke="var(--green)" strokeWidth="7" strokeDasharray={`${pct/100*c} ${c}`} transform="rotate(-90 35 35)" strokeLinecap="round"/><text x="35" y="39" textAnchor="middle" className="ring-value">{Math.round(pct)}%</text></svg><strong>{g.description||"Meta"}</strong><span>{cur} / {target}</span><small>{formatDate(g.due_date)} · {g.status||"—"}</small></div>;})}</div>; }
function Timeline({items=[],empty="Sem registros."}) { if(!items.length)return <div className="chart-empty">{empty}</div>; return <div className="timeline">{items.map((x,i)=><div className="timeline-item" key={x.id||i}><div className="timeline-dot"/><div><strong>{x.title}</strong><span>{x.date}</span>{x.detail&&<p>{x.detail}</p>}</div></div>)}</div>; }
function TrendChart({items=[]}) { if(!items.length)return null; const vals=items.map(x=>Number(x.overall_score||0)),w=620,h=230,p=35,max=Math.max(10,...vals); const points=vals.map((v,i)=>{const x=p+(items.length===1?0:i*(w-p*2)/(items.length-1));const y=h-p-v/max*(h-p*2);return [x,y];}); return <svg className="trend-svg" viewBox={`0 0 ${w} ${h}`} role="img" aria-label="Evolução das avaliações"><line x1={p} y1={h-p} x2={w-p} y2={h-p} className="chart-axis"/><polyline points={points.map(a=>a.join(",")).join(" ")} className="trend-line"/>{points.map(([x,y],i)=><g key={i}><circle cx={x} cy={y} r="5" className="trend-dot"/><text x={x} y={y-10} textAnchor="middle" className="trend-value">{vals[i].toFixed(1)}</text><text x={x} y={h-8} textAnchor="middle" className="trend-label">{String(items[i].cycle_name||"Ciclo").slice(0,12)}</text></g>)}</svg>; }

function NineBox({ rows=[] }) {
  const latest = rows[0];
  const label = latest ? `Desempenho ${latest.performance_level} × Potencial ${latest.potential_level}` : "Sem classificação registrada";
  return <div className="ninebox-wrap"><div className="ninebox-head"><div><strong>Matriz de Potencial × Desempenho</strong><span>{latest?.cycle_name || "Nenhum ciclo selecionado"}</span></div><b>{label}</b></div><div className="ninebox"><div className="ninebox-y">POTENCIAL</div><div className="ninebox-grid">{[3,2,1].map(p=>[3,2,1].map(d=>{const active=latest&&latest.performance_level===d&&latest.potential_level===p;return <div key={`${p}-${d}`} className={`nine-cell n${p}${d} ${active?"active":""}`}><strong>{p===3?"Alto":p===2?"Médio":"Baixo"}</strong><span>{d===3?"Alto":d===2?"Médio":"Baixo"}</span>{active&&<em>COLABORADOR</em>}</div>;}))}</div></div><div className="ninebox-x">DESEMPENHO</div>{latest?.notes&&<div className="justification"><strong>Justificativa / observações</strong><p>{latest.notes}</p></div>}{!latest&&<div className="chart-empty">A Matriz Nine Box está integrada à Central. Registre um ciclo para posicionar o colaborador.</div>}</div>;
}

function printRadar(items,title,max=10){const safe=items.filter(x=>Number.isFinite(Number(x.value))).slice(0,12);if(safe.length<3)return "";const size=420,c=210,r=125;const pts=vals=>vals.map((v,i)=>{const [x,y]=polar(c,c,Math.max(0,Math.min(max,Number(v)))/max*r,i*Math.PI*2/vals.length);return `${x.toFixed(1)},${y.toFixed(1)}`;}).join(" ");return `<div class="chart-wrap"><div class="chart-title">${title} · escala 0–${max}</div><svg viewBox="0 0 ${size} ${size}" width="420" height="420">${[25,50,75,100].map(v=>{const n=max===100?v:v/10*max;return `<polygon points="${pts(safe.map(()=>n))}" fill="none" stroke="#dfe4eb"/>`;}).join("")}<polygon points="${pts(safe.map(x=>x.value))}" fill="#2563EB" fill-opacity=".18" stroke="#2563EB" stroke-width="3"/>${safe.map((x,i)=>{const [px,py]=polar(c,c,Math.max(0,Math.min(max,Number(x.value)))/max*r,i*Math.PI*2/safe.length);return `<circle cx="${px}" cy="${py}" r="5" fill="#2563EB"/><text x="${px}" y="${py-9}" text-anchor="middle" font-size="11" font-weight="700">${Number(x.value).toFixed(1)}</text>`;}).join("")}</svg></div>`;}
function printTrend(items){if(!items.length)return "";const vals=items.map(x=>Number(x.overall_score||0)),w=700,h=260,p=45,max=Math.max(10,...vals),pts=vals.map((v,i)=>{const x=p+(items.length===1?0:i*(w-p*2)/(items.length-1));const y=h-p-v/max*(h-p*2);return [x,y];});return `<div class="chart-wrap"><div class="chart-title">Evolução histórica das avaliações</div><svg viewBox="0 0 ${w} ${h}" width="700" height="260"><line x1="${p}" y1="${h-p}" x2="${w-p}" y2="${h-p}" stroke="#dfe4eb"/><polyline points="${pts.map(a=>a.join(",")).join(" ")}" fill="none" stroke="#2563EB" stroke-width="4"/>${pts.map(([x,y],i)=>`<circle cx="${x}" cy="${y}" r="6" fill="#2563EB"/><text x="${x}" y="${y-12}" text-anchor="middle" font-size="12" font-weight="700">${vals[i].toFixed(1)}</text><text x="${x}" y="${h-12}" text-anchor="middle" font-size="10">${String(items[i].cycle_name||"Ciclo").slice(0,16)}</text>`).join("")}</svg></div>`;}
function printNineBox(row){if(!row)return `<div class="highlight"><strong>Matriz Nine Box</strong><p>Não há classificação Nine Box registrada para este colaborador.</p></div>`;return `<div class="ninebox-print"><div class="ninebox-print-grid">${[3,2,1].map(p=>[1,2,3].map(d=>`<div class="nbp n${p}${d} ${row.performance_level===d&&row.potential_level===p?"active":""}"><b>${p}/${d}</b>${row.performance_level===d&&row.potential_level===p?"<span>COLABORADOR</span>":""}</div>`).join("")).join("")}</div><p><strong>Posição:</strong> desempenho ${row.performance_level}/3 · potencial ${row.potential_level}/3 · ciclo ${row.cycle_name||"—"}</p>${row.notes?`<div class="justification"><strong>Justificativa / observações</strong><p>${row.notes}</p></div>`:""}</div>`;}

export default function CentralAvaliacoesPage(){
  const {company,profile}=useAuth(); const role=String(profile?.access_role||"employee").toLowerCase(); const isEmployee=role==="employee";
  const [employees,setEmployees]=useState([]),[employeeId,setEmployeeId]=useState(""); const [evaluations,setEvaluations]=useState([]),[scores,setScores]=useState([]),[behavior,setBehavior]=useState([]),[experience,setExperience]=useState([]),[goals,setGoals]=useState([]),[pdi,setPdi]=useState([]),[feedbacks,setFeedbacks]=useState([]),[ninebox,setNinebox]=useState([]),[evaluatorNames,setEvaluatorNames]=useState({});
  const [tab,setTab]=useState("desempenho"),[loading,setLoading]=useState(true),[error,setError]=useState(""),[printing,setPrinting]=useState(false);
  async function load(){if(!company?.id||!profile?.id)return;setLoading(true);setError("");try{let eq=supabase.from("employees").select("id,full_name,role,manager_id,profile_id").eq("company_id",company.id).eq("status","ativo").order("full_name");if(isEmployee)eq=eq.eq("profile_id",profile.id);else if(role==="gestor"){const me=await supabase.from("employees").select("id").eq("company_id",company.id).eq("profile_id",profile.id).maybeSingle();if(me.error)throw me.error;if(me.data)eq=eq.eq("manager_id",me.data.id);}const results=await Promise.all([eq,supabase.from("hr_performance_evaluations").select("id,employee_id,cycle_name,evaluation_type,evaluator_profile_id,status,overall_score,comments,created_at").eq("company_id",company.id).order("created_at",{ascending:false}),supabase.from("hr_behavioral_assessments").select("id,employee_id,assessment_date,dominance,influence,steadiness,compliance,notes").eq("company_id",company.id).order("assessment_date",{ascending:false}),supabase.from("hr_experience_evaluations").select("id,employee_id,admission_date,first_period_end,second_period_end,first_result,first_notes,first_evaluated_at,second_result,second_notes,second_evaluated_at,final_decision,created_at").eq("company_id",company.id),supabase.from("hr_goals").select("id,employee_id,description,target_value,current_value,due_date,status").eq("company_id",company.id),supabase.from("hr_pdi").select("id,employee_id,action_description,target_date,status").eq("company_id",company.id),supabase.from("hr_feedbacks").select("id,employee_id,author_profile_id,feedback_type,context,strengths,development_points,action_plan,comment,feedback_date,status").eq("company_id",company.id).order("feedback_date",{ascending:false}),supabase.from("hr_nine_box").select("id,employee_id,cycle_name,performance_level,potential_level,notes,created_at").eq("company_id",company.id).order("created_at",{ascending:false})]);const bad=results.find(x=>x.error);if(bad)throw bad.error;setEmployees(results[0].data||[]);setEvaluations(results[1].data||[]);setBehavior(results[2].data||[]);setExperience(results[3].data||[]);setGoals(results[4].data||[]);setPdi(results[5].data||[]);setFeedbacks(results[6].data||[]);setNinebox(results[7].data||[]);const ids=[...(results[1].data||[]).map(x=>x.evaluator_profile_id),...(results[6].data||[]).map(x=>x.author_profile_id)].filter(Boolean);if(ids.length){const {data:p}=await supabase.from("profiles").select("id,full_name").in("id",[...new Set(ids)]);setEvaluatorNames(Object.fromEntries((p||[]).map(x=>[x.id,x.full_name])));}if(results[0].data?.length)setEmployeeId(prev=>isEmployee||!prev?results[0].data[0].id:prev);else setEmployeeId("");}catch(e){setError(e.message||"Não foi possível carregar as avaliações.");}finally{setLoading(false);}}
  useEffect(()=>{load();},[company?.id,profile?.id,role]);
  useEffect(()=>{(async()=>{if(!employeeId){setScores([]);return;}const ids=evaluations.filter(x=>x.employee_id===employeeId).map(x=>x.id);if(!ids.length){setScores([]);return;}const {data,error:e}=await supabase.from("hr_evaluation_scores").select("id,evaluation_id,competency_id,score,comments,hr_competencies:competency_id(id,name,category,description)").in("evaluation_id",ids);if(e)setError(e.message);else setScores(data||[]);})();},[employeeId,evaluations]);
  const employee=employees.find(x=>x.id===employeeId),ev=evaluations.filter(x=>x.employee_id===employeeId),bh=behavior.filter(x=>x.employee_id===employeeId),ex=experience.filter(x=>x.employee_id===employeeId),gm=goals.filter(x=>x.employee_id===employeeId),pd=pdi.filter(x=>x.employee_id===employeeId),fb=feedbacks.filter(x=>x.employee_id===employeeId),nb=ninebox.filter(x=>x.employee_id===employeeId);
  const comps=useMemo(()=>{const m={};scores.forEach(x=>{const c=x.hr_competencies;if(!c)return;(m[c.id]??={id:c.id,name:c.name,category:c.category,description:c.description,values:[],comments:[]}).values.push(Number(x.score||0));if(x.comments)m[c.id].comments.push(x.comments);});return Object.values(m).map(x=>({...x,value:x.values.reduce((a,b)=>a+b,0)/x.values.length,comment:x.comments.join(" • ")}));},[scores]);
  const overall=comps.length?comps.reduce((a,b)=>a+b.value,0)/comps.length:Number(ev[0]?.overall_score||0),latestDisc=bh[0];
  const chart360=useMemo(()=>Object.keys(TYPE_LABEL).map(t=>{const a=ev.filter(x=>x.evaluation_type===t&&x.overall_score!=null);return {label:TYPE_LABEL[t],value:a.length?a.reduce((s,x)=>s+Number(x.overall_score),0)/a.length:0};}).filter(x=>x.value>0),[ev]);
  const trend=useMemo(()=>ev.filter(x=>x.overall_score!=null).slice().reverse().slice(-8),[ev]); const feedbackDist=useMemo(()=>{const m={};fb.forEach(x=>{const k=x.feedback_type||"Outros";m[k]=(m[k]||0)+1;});return Object.entries(m).map(([label,value])=>({label,value}));},[fb]); const discItems=latestDisc?DISC.map(([key,short])=>({name:short,value:Number(latestDisc[key]||0)})):[];

  async function printFullEvaluation(){if(!employee||printing)return;setPrinting(true);try{const scoreRows=scores.map(x=>[x.hr_competencies?.name||"Competência",x.hr_competencies?.category||"—",x.score??"—",x.comments||"Sem justificativa registrada"]),evalRows=ev.map(x=>[x.cycle_name||"—",TYPE_LABEL[x.evaluation_type]||x.evaluation_type||"—",evaluatorNames[x.evaluator_profile_id]||"—",x.status||"—",x.overall_score!=null?Number(x.overall_score).toFixed(1):"—",formatDate(x.created_at),x.comments||"Sem justificativa registrada"]),behaviorRows=bh.map(x=>[formatDate(x.assessment_date),x.dominance,x.influence,x.steadiness,x.compliance,x.notes||"Sem justificativa registrada"]),expRows=ex.map(x=>[formatDate(x.admission_date),formatDate(x.first_period_end),x.first_result||"—",x.first_notes||"Sem justificativa registrada",formatDate(x.second_period_end),x.second_result||"—",x.second_notes||"Sem justificativa registrada",x.final_decision||"—"]),goalRows=gm.map(x=>[x.description||"—",x.current_value??"—",x.target_value??"—",formatDate(x.due_date),x.status||"—"]),feedbackRows=fb.map(x=>[x.feedback_type||"—",formatDate(x.feedback_date),evaluatorNames[x.author_profile_id]||"—",x.context||"—",x.strengths||"—",x.development_points||"—",x.action_plan||"—",x.comment||"—",x.status||"—"]),pdiRows=pd.map(x=>[x.action_description||"—",formatDate(x.target_date),x.status||"—"]);let content=section("Identificação",infoGrid([{label:"Colaborador",value:employee.full_name},{label:"Cargo",value:employee.role||"—"},{label:"Empresa",value:company?.name||"—"}]))+kpis([{label:"Nota geral",value:overall?overall.toFixed(1):"—"},{label:"Avaliações",value:ev.length},{label:"Feedbacks",value:fb.length},{label:"Metas",value:gm.length}]);
    if(comps.length)content+=section("1. Avaliação de Desempenho e Competências",printRadar(comps,"Perfil de Competências",10)+table(["Competência","Categoria","Nota","Justificativa / comentário"],scoreRows));
    if(chart360.length)content+=section("2. Avaliação 360°",printRadar(chart360,"Comparativo dos avaliadores",10)+table(["Perfil","Média"],chart360.map(x=>[x.label,Number(x.value).toFixed(1)]))+table(["Ciclo","Tipo","Avaliador","Status","Nota","Data","Justificativa"],evalRows));
    if(latestDisc)content+=section("3. Avaliação Comportamental — DISC",printRadar(discItems,"Perfil DISC",100)+table(["Fator","Pontuação"],discItems.map(x=>[x.name,x.value]))+`<div class="justification"><strong>Justificativa / observações</strong><p>${latestDisc.notes||"Sem justificativa registrada."}</p></div>`+table(["Data","D","I","S","C","Observações"],behaviorRows));
    if(ex.length)content+=section("4. Avaliação de Experiência",table(["Admissão","Fim 1º período","Resultado 1","Justificativa 1","Fim 2º período","Resultado 2","Justificativa 2","Decisão final"],expRows));
    if(gm.length)content+=section("5. Metas e resultados",`<div class="goal-summary">${gm.map(g=>{const cur=Number(g.current_value||0),target=Number(g.target_value||0),pct=target>0?Math.max(0,Math.min(100,cur/target*100)):0;return `<div class="highlight"><strong>${g.description||"Meta"}</strong><p><b>${Math.round(pct)}%</b> de atingimento · Atual ${cur} · Alvo ${target} · Prazo ${formatDate(g.due_date)} · ${g.status||"—"}</p><p class="note"><strong>Justificativa:</strong> o cadastro atual da meta não possui campo próprio de justificativa.</p></div>`}).join("")}</div>`+table(["Meta","Atual","Alvo","Prazo","Status"],goalRows));
    if(fb.length)content+=section("6. Feedbacks",table(["Tipo","Data","Autor","Contexto","Pontos fortes","Desenvolvimento","Plano de ação","Comentário","Status"],feedbackRows));
    if(pd.length)content+=section("7. Plano de Desenvolvimento Individual",table(["Ação","Data alvo","Status"],pdiRows)+`<div class="justification"><strong>Justificativa / contexto</strong><p>O cadastro atual do PDI possui ação, prazo e status, mas ainda não possui campo próprio de justificativa.</p></div>`);
    content+=section("8. Matriz Nine Box",printNineBox(nb[0]));
    if(trend.length)content+=section("9. Evolução histórica",printTrend(trend));
    openPrintDocument({title:"Relatório Executivo de Avaliações e Desenvolvimento",subtitle:employee.full_name,company:{name:company?.name},content,documentCode:"PP-AVL-EXEC"});
  }catch(e){setError(e.message||"Não foi possível preparar a impressão.");}finally{setPrinting(false);}}
  if(loading)return <div className="report-page"><div className="loading-state">Carregando avaliações...</div></div>;
  return <div className="report-page"><div className="no-print"><div className="page-header"><div><span className="eyebrow">Central de Avaliações</span><h1>{isEmployee?"Minhas Avaliações":"Central de Avaliações"}</h1><p>Desempenho, comportamento, experiência, desenvolvimento, potencial e histórico em uma única visão.</p></div><div className="header-actions">{!isEmployee&&<select value={employeeId} onChange={e=>setEmployeeId(e.target.value)}><option value="">Selecione o colaborador</option>{employees.map(e=><option key={e.id} value={e.id}>{e.full_name}</option>)}</select>}<button className="btn btn-primary" onClick={printFullEvaluation} disabled={!employee||printing}>{printing?"Preparando...":"🖨 Relatório executivo completo"}</button></div></div>{error&&<div className="alert alert-error">{error}</div>}{!employee?<div className="empty-state">Selecione um colaborador para visualizar as avaliações.</div>:<><div className="eval-profile"><div><strong>{employee.full_name}</strong><span>{employee.role||"Cargo não informado"}</span></div><div className="eval-score"><small>Nota geral</small><b>{overall?overall.toFixed(1):"—"}</b></div></div><div className="eval-tabs">{TABS.map(([key,label])=><button key={key} className={tab===key?"active":""} onClick={()=>setTab(key)}>{label}</button>)}</div><div className="eval-content">
    {tab==="desempenho"&&<><div className="eval-chart-grid"><RadarChart items={comps.slice(0,10)} title="Desempenho por competência"/><RadarChart items={chart360} title="Visão 360°"/></div><section className="card"><h2>Evolução das avaliações</h2>{trend.length?<TrendChart items={trend}/>:<div className="chart-empty">Sem histórico de notas.</div>}</section></>}
    {tab==="360"&&<section className="card"><h2>Avaliação 360°</h2><RadarChart items={chart360} title="Comparação dos avaliadores"/><div className="history-list">{ev.map(x=><div key={x.id}><strong>{x.cycle_name||"Ciclo"}</strong><span>{TYPE_LABEL[x.evaluation_type]||x.evaluation_type||"—"}</span><b>{x.overall_score!=null?Number(x.overall_score).toFixed(1):"—"}</b><small>{evaluatorNames[x.evaluator_profile_id]||"—"}</small><p>{x.comments||"Sem justificativa registrada."}</p></div>)}</div></section>}
    {tab==="comportamental"&&<section className="card"><h2>Perfil comportamental — DISC</h2><RadarChart items={discItems} max={100} title="Perfil DISC"/>{latestDisc?.notes&&<div className="justification"><strong>Justificativa / observações</strong><p>{latestDisc.notes}</p></div>}</section>}
    {tab==="experiencia"&&<section className="card"><h2>Experiência do colaborador</h2><Timeline items={ex.map(x=>({id:x.id,title:x.final_decision||"Avaliação de experiência",date:formatDate(x.admission_date),detail:[`1º período: ${x.first_result||"—"}`,x.first_notes&&`Justificativa: ${x.first_notes}`,`2º período: ${x.second_result||"—"}`,x.second_notes&&`Justificativa: ${x.second_notes}`].filter(Boolean).join(" • ")}))} empty="Nenhuma avaliação de experiência registrada."/></section>}
    {tab==="competencias"&&<section className="card"><h2>Mapa de competências</h2><RadarChart items={comps.slice(0,12)} title="Competências"/><div className="feedback-list">{comps.map(c=><article key={c.id}><strong>{c.name}</strong><span>{Number(c.value).toFixed(1)} / 10</span><p>{c.description||""}{c.comment&&` — ${c.comment}`}</p></article>)}</div></section>}
    {tab==="metas"&&<section className="card"><h2>Metas e atingimento</h2><GoalRings goals={gm}/></section>}
    {tab==="feedbacks"&&<section className="card"><h2>Feedbacks</h2><DonutChart items={feedbackDist} title="Distribuição dos feedbacks"/><div className="feedback-list">{fb.map(f=><article key={f.id}><strong>{f.feedback_type||"Feedback"}</strong><span>{formatDate(f.feedback_date)} · {evaluatorNames[f.author_profile_id]||"Autor não informado"}</span><p>{[f.context,f.strengths,f.development_points,f.action_plan,f.comment].filter(Boolean).join(" • ")||"Sem conteúdo registrado."}</p></article>)}</div></section>}
    {tab==="pdi"&&<section className="card"><h2>Plano de Desenvolvimento Individual</h2><Timeline items={pd.map(x=>({id:x.id,title:x.action_description||"Ação de desenvolvimento",date:formatDate(x.target_date),detail:x.status||""}))} empty="Nenhuma ação de PDI registrada."/><div className="justification"><strong>Observação</strong><p>O cadastro atual do PDI ainda não possui campo específico para justificativa.</p></div></section>}
    {tab==="ninebox"&&<section className="card"><h2>Matriz Nine Box</h2><NineBox rows={nb}/></section>}
    {tab==="historico"&&<section className="card"><h2>Histórico de avaliações</h2>{trend.length?<TrendChart items={trend}/>:<div className="chart-empty">Sem histórico de notas.</div>}<div className="history-list">{ev.map(x=><div key={x.id}><strong>{x.cycle_name||"Ciclo"}</strong><span>{TYPE_LABEL[x.evaluation_type]||x.evaluation_type||"—"}</span><b>{x.overall_score!=null?Number(x.overall_score).toFixed(1):"—"}</b><small>{formatDate(x.created_at)}</small><p>{x.comments||"Sem justificativa registrada."}</p></div>)}</div></section>}
  </div></>}</div></div>;
}
