import { useEffect, useState } from "react";
import { supabase } from "../lib/supabaseClient";
import { useAuth } from "../lib/AuthContext";

export default function ComunicadosPage(){
 const {company,profile}=useAuth(); const [employees,setEmployees]=useState([]),[items,setItems]=useState([]),[title,setTitle]=useState(""),[content,setContent]=useState(""),[type,setType]=useState("comunicado"),[requiresAck,setRequiresAck]=useState(true),[due,setDue]=useState(""),[file,setFile]=useState(null),[targets,setTargets]=useState([]),[all,setAll]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState("");
 async function load(){if(!company?.id)return;const [{data:e},{data:c}]=await Promise.all([supabase.from("employees").select("id,full_name,role").eq("status","ativo").order("full_name"),supabase.from("hr_communications").select("id,title,communication_type,requires_ack,due_at,version,status,created_at").order("created_at",{ascending:false})]);setEmployees(e||[]);setItems(c||[])}
 useEffect(()=>{load()},[company?.id]);
 function toggle(id){setTargets(v=>v.includes(id)?v.filter(x=>x!==id):[...v,id])}
 async function publish(e){e.preventDefault();setError("");if(!title)return setError("Informe o título.");if(!all&&!targets.length)return setError("Selecione os destinatários ou marque Todos.");setSaving(true);try{let path=null;if(file){path=`${company.id}/${crypto.randomUUID()}-${file.name}`;const {error}=await supabase.storage.from("prodpersonal-documents").upload(path,file);if(error)throw error}const {data:comm,error:ce}=await supabase.from("hr_communications").insert({company_id:company.id,title,content,communication_type:type,file_path:path,file_name:file?.name||null,requires_ack:requiresAck,due_at:due?new Date(due).toISOString():null,created_by:profile?.id,published_at:new Date().toISOString(),status:"published"}).select("id").single();if(ce)throw ce;const ids=all?employees.map(x=>x.id):targets;const {error:re}=await supabase.from("hr_communication_recipients").insert(ids.map(employee_id=>({company_id:company.id,communication_id:comm.id,employee_id,status:"pending"})));if(re)throw re;setTitle("");setContent("");setFile(null);setTargets([]);setAll(false);setDue("");await load()}catch(err){setError(err.message||"Não foi possível publicar.")}finally{setSaving(false)}}
 return <div><header style={styles.header}><h1 style={styles.title}>Comunicados e Documentos</h1><p style={styles.sub}>Envie informações para todos ou para colaboradores selecionados e acompanhe ciência, aceite e recusa.</p></header>{error&&<div style={styles.error}>{error}</div>}<div style={styles.grid}><form onSubmit={publish} style={styles.card}><h3>Novo comunicado</h3><input style={styles.input} placeholder="Título" value={title} onChange={e=>setTitle(e.target.value)}/><textarea style={styles.textarea} placeholder="Mensagem / instruções" value={content} onChange={e=>setContent(e.target.value)}/><div style={styles.row}><select style={styles.input} value={type} onChange={e=>setType(e.target.value)}><option value="comunicado">Comunicado</option><option value="documento">Documento</option><option value="politica">Política</option><option value="termo">Termo</option></select><input style={styles.input} type="datetime-local" value={due} onChange={e=>setDue(e.target.value)}/></div><label style={styles.check}><input type="checkbox" checked={requiresAck} onChange={e=>setRequiresAck(e.target.checked)}/> Exigir ciência/aceite</label><input type="file" onChange={e=>setFile(e.target.files?.[0]||null)}/><div style={styles.targetHeader}><strong>Destinatários</strong><label><input type="checkbox" checked={all} onChange={e=>{setAll(e.target.checked);if(e.target.checked)setTargets([])}}/> Todos</label></div><div style={styles.targets}>{employees.map(x=><label key={x.id}><input type="checkbox" checked={targets.includes(x.id)} disabled={all} onChange={()=>toggle(x.id)}/> {x.full_name} <small>{x.role}</small></label>)}</div><button style={styles.button} disabled={saving}>{saving?"Publicando...":"Publicar comunicado"}</button></form><section style={styles.card}><h3>Publicados</h3>{items.length?items.map(x=><div key={x.id} style={styles.item}><div><strong>{x.title}</strong><small>{x.communication_type} · v{x.version}{x.requires_ack?" · exige ciência":""}</small></div><span>{new Date(x.created_at).toLocaleDateString("pt-BR")}</span></div>):<p style={styles.dim}>Nenhum comunicado publicado.</p>}<p style={styles.note}>Cada destinatário possui seu próprio status: Pendente, Visualizado, Ciente/Aceito ou Recusado. A recusa deve registrar justificativa.</p></section></div></div>;
}
const styles={title:{fontFamily:"var(--font-display)",fontSize:24,margin:0},sub:{color:"var(--text-dim)",fontSize:13,margin:"6px 0 0"},header:{marginBottom:18},grid:{display:"grid",gridTemplateColumns:"minmax(360px,1fr) minmax(320px,1fr)",gap:16},card:{background:"var(--panel)",border:"1px solid var(--line)",borderRadius:"var(--radius)",padding:18},input:{width:"100%",boxSizing:"border-box",background:"var(--panel-2)",border:"1px solid var(--line)",borderRadius:"var(--radius)",padding:"9px 10px",color:"var(--text)",fontSize:13},textarea:{width:"100%",boxSizing:"border-box",minHeight:110,background:"var(--panel-2)",border:"1px solid var(--line)",borderRadius:"var(--radius)",padding:10,color:"var(--text)",fontSize:13,margin:"10px 0"},row:{display:"flex",gap:10},check:{display:"block",margin:"12px 0",fontSize:13},targetHeader:{display:"flex",justifyContent:"space-between",margin:"16px 0 8px"},targets:{maxHeight:220,overflowY:"auto",display:"flex",flexDirection:"column",gap:7,padding:10,background:"var(--panel-2)",borderRadius:"var(--radius)"},button:{marginTop:16,width:"100%",background:"var(--amber)",color:"#fff",border:0,borderRadius:"var(--radius)",padding:10,fontWeight:700,cursor:"pointer"},item:{display:"flex",justifyContent:"space-between",gap:10,padding:"12px 0",borderBottom:"1px solid var(--line)",fontSize:13},dim:{color:"var(--text-dim)",fontSize:12.5},note:{marginTop:16,color:"var(--text-dim)",fontSize:12},error:{padding:10,marginBottom:12,color:"var(--red)",border:"1px solid var(--red)",borderRadius:"var(--radius)"}};
