import {useEffect,useState} from "react";
import {supabase} from "../lib/supabaseClient";
import {useAuth} from "../lib/AuthContext";
const TYPES=["Reconhecimento","Desenvolvimento","1:1","Pós-avaliação","Outro"];
export default function FeedbacksPage(){
 const {company,profile}=useAuth();const role=profile?.access_role||"employee",isEmployee=role==="employee",canConfigure=["rh","dp","admin","master"].includes(role);
 const [employees,setEmployees]=useState([]),[managers,setManagers]=useState([]),[rows,setRows]=useState([]),[employeeId,setEmployeeId]=useState(""),[managerId,setManagerId]=useState(""),[enabled,setEnabled]=useState(false),[form,setForm]=useState({feedback_type:"Desenvolvimento",context:"",strengths:"",development_points:"",action_plan:"",comment:""}),[open,setOpen]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(""),[saving,setSaving]=useState(false);
 async function load(){if(!company?.id||!profile?.id)return;setLoading(true);setError("");try{
   const settingsPromise=supabase.from("hr_company_settings").select("feedback_to_managers_enabled").eq("company_id",company.id).maybeSingle();
   let empQ=supabase.from("employees").select("id,full_name,role,manager_id,profile_id").eq("company_id",company.id).eq("status","ativo").order("full_name");
   if(isEmployee)empQ=empQ.eq("profile_id",profile.id);else if(role==="gestor")empQ=empQ.eq("manager_id",profile.id);
   const [settingsRes,empRes,fbRes]=await Promise.all([settingsPromise,empQ,supabase.from("hr_feedbacks").select("id,employee_id,author_profile_id,feedback_type,context,strengths,development_points,action_plan,comment,feedback_date,status,created_at").eq("company_id",company.id).order("feedback_date",{ascending:false})]);
   if(settingsRes.error)throw settingsRes.error;if(empRes.error)throw empRes.error;if(fbRes.error)throw fbRes.error;setEnabled(settingsRes.data?.feedback_to_managers_enabled===true);
   const es=empRes.data||[];setEmployees(es);setRows(fbRes.data||[]);
   if(isEmployee){const {data:all}=await supabase.from("employees").select("id,full_name,role,profile_id").eq("company_id",company.id).eq("status","ativo").order("full_name");const {data:ps,error:pe}=await supabase.from("profiles").select("id").eq("company_id",company.id).eq("access_role","gestor");if(pe)throw pe;const ids=new Set((ps||[]).map(p=>p.id));const ms=(all||[]).filter(e=>ids.has(e.profile_id));setManagers(ms);if(!managerId&&ms[0])setManagerId(ms[0].id);}else if(!employeeId&&es[0])setEmployeeId(es[0].id);
 }catch(e){setError(e.message||"Não foi possível carregar os feedbacks.")}finally{setLoading(false)}}
 useEffect(()=>{load()},[company?.id,profile?.id,role]);
 async function toggleRelease(){const next=!enabled;setError("");const {error}=await supabase.from("hr_company_settings").upsert({company_id:company.id,feedback_to_managers_enabled:next,updated_at:new Date().toISOString()},{onConflict:"company_id"});if(error)setError(error.message);else setEnabled(next)}
 async function save(e){e.preventDefault();const targetId=isEmployee?managerId:employeeId;if(!targetId)return setError(isEmployee?"Selecione um gestor.":"Selecione um colaborador.");if(isEmployee&&!enabled)return setError("O RH ainda não liberou a avaliação dos gestores.");setSaving(true);const {error}=await supabase.from("hr_feedbacks").insert({...form,company_id:company.id,employee_id:targetId,author_profile_id:profile.id,status:"registrado"});if(error)setError(error.message);else{setForm({feedback_type:"Desenvolvimento",context:"",strengths:"",development_points:"",action_plan:"",comment:""});setOpen(false);await load()}setSaving(false)}
 const visibleRows=isEmployee?rows.filter(r=>r.employee_id===employees[0]?.id||r.author_profile_id===profile.id):rows.filter(r=>r.employee_id===employeeId);
 return <div><header style={s.header}><div><div style={s.kicker}>Desenvolvimento</div><h1 style={s.title}>{isEmployee?"Meus Feedbacks":"Feedbacks"}</h1><p style={s.sub}>{isEmployee?"Consulte os feedbacks que recebeu.":"Registre e acompanhe conversas de desenvolvimento."}</p></div><div className="no-print" style={s.actions}><button style={s.btnGhost} onClick={()=>window.print()}>🖨 Imprimir</button>{(!isEmployee||enabled)&&<button style={s.btn} onClick={()=>setOpen(!open)}>{open?"Cancelar":"+ Novo feedback"}</button>}</div></header>
 {canConfigure&&<div className="no-print" style={s.release}><div><b>Avaliação de gestores pelos colaboradores</b><p>Libere ou bloqueie a função para toda a empresa.</p></div><button style={{...s.toggle,...(enabled?s.on:{})}} onClick={toggleRelease}>{enabled?"Liberada":"Bloqueada"}</button></div>}
 {isEmployee&&!enabled&&<div className="no-print" style={s.notice}>A avaliação dos gestores ainda não foi liberada pelo RH.</div>}
 {!isEmployee&&<div className="no-print" style={s.selector}><label>Colaborador<select value={employeeId} onChange={e=>setEmployeeId(e.target.value)} style={s.input}>{employees.map(e=><option key={e.id} value={e.id}>{e.full_name} — {e.role||"Sem cargo"}</option>)}</select></label></div>}
 {isEmployee&&enabled&&<div className="no-print" style={s.selector}><label>Gestor que você deseja avaliar<select value={managerId} onChange={e=>setManagerId(e.target.value)} style={s.input}>{managers.map(e=><option key={e.id} value={e.id}>{e.full_name} — {e.role||"Gestor"}</option>)}</select></label></div>}
 {error&&<div style={s.error}>{error}</div>}{open&&<form className="no-print" onSubmit={save} style={s.form}><label>Tipo<select style={s.input} value={form.feedback_type} onChange={e=>setForm({...form,feedback_type:e.target.value})}>{TYPES.map(x=><option key={x}>{x}</option>)}</select></label>{[["context","Contexto"],["strengths","Pontos positivos"],["development_points","Pontos de desenvolvimento"],["action_plan","Plano de ação"],["comment","Comentário geral"]].map(([k,l])=><label key={k}>{l}<textarea style={{...s.input,minHeight:75}} value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/></label>)}<button style={s.btn} type="submit" disabled={saving}>{saving?"Registrando...":"Registrar feedback"}</button></form>}
 <section style={s.card}><div style={s.cardHead}><h2>{isEmployee?"Feedbacks recebidos":"Feedbacks do colaborador"}</h2><span>{visibleRows.length} registro(s)</span></div>{loading?<p style={s.dim}>Carregando...</p>:visibleRows.length===0?<p style={s.dim}>{isEmployee?"Você ainda não recebeu feedbacks registrados.":"Nenhum feedback registrado."}</p>:visibleRows.map(r=><article key={r.id} style={s.item}><div style={s.itemTop}><strong>{r.feedback_type}</strong><span>{r.feedback_date?new Date(r.feedback_date).toLocaleDateString("pt-BR"):"—"}</span></div>{r.context&&<p><b>Contexto:</b> {r.context}</p>}{r.strengths&&<p><b>Pontos positivos:</b> {r.strengths}</p>}{r.development_points&&<p><b>Desenvolvimento:</b> {r.development_points}</p>}{r.action_plan&&<p><b>Plano de ação:</b> {r.action_plan}</p>}{r.comment&&<p><b>Comentário:</b> {r.comment}</p>}</article>)}</section></div>;
}
const s={header:{display:"flex",justifyContent:"space-between",alignItems:"end",gap:16,marginBottom:18},kicker:{fontSize:11,fontWeight:800,textTransform:"uppercase",letterSpacing:".08em",color:"var(--amber)"},title:{fontFamily:"var(--font-display)",fontSize:24,margin:0},sub:{color:"var(--text-dim)",fontSize:13,margin:"6px 0 0"},actions:{display:"flex",gap:8},btn:{background:"var(--amber)",color:"#fff",border:0,borderRadius:"var(--radius)",padding:"9px 14px",fontWeight:700,cursor:"pointer"},btnGhost:{background:"var(--panel)",color:"var(--text)",border:"1px solid var(--line)",borderRadius:"var(--radius)",padding:"9px 14px",fontWeight:700,cursor:"pointer"},release:{display:"flex",justifyContent:"space-between",alignItems:"center",gap:20,background:"var(--panel)",border:"1px solid var(--line)",borderRadius:"var(--radius)",padding:16,marginBottom:16},toggle:{border:"1px solid var(--line)",background:"var(--panel-2)",color:"var(--text-dim)",borderRadius:"999px",padding:"8px 16px",fontWeight:800,cursor:"pointer"},on:{background:"var(--green)",color:"#fff",borderColor:"var(--green)"},notice:{padding:12,marginBottom:16,border:"1px solid var(--line)",borderRadius:"var(--radius)",color:"var(--text-dim)"},selector:{background:"var(--panel)",border:"1px solid var(--line)",borderRadius:"var(--radius)",padding:16,marginBottom:16},input:{display:"block",width:"100%",marginTop:6,background:"var(--panel-2)",border:"1px solid var(--line)",borderRadius:"var(--radius)",padding:"9px",color:"var(--text)"},form:{display:"grid",gap:12,background:"var(--panel)",border:"1px solid var(--line)",borderRadius:"var(--radius)",padding:18,marginBottom:16},card:{background:"var(--panel)",border:"1px solid var(--line)",borderRadius:"var(--radius)",padding:18},cardHead:{display:"flex",justifyContent:"space-between",alignItems:"center",borderBottom:"1px solid var(--line)",paddingBottom:12,marginBottom:12},item:{borderBottom:"1px solid var(--line)",padding:"14px 0"},itemTop:{display:"flex",justifyContent:"space-between",marginBottom:8},dim:{color:"var(--text-dim)"},error:{padding:10,marginBottom:12,color:"var(--red)",border:"1px solid var(--red)",borderRadius:"var(--radius)"}};