import { useEffect, useState } from "react";
import { supabase } from "../lib/supabaseClient";
import { useAuth } from "../lib/AuthContext";

const TYPES=["Reconhecimento","Desenvolvimento","1:1","Pós-avaliação","Outro"];
export default function FeedbacksPage(){
 const {company,profile}=useAuth(); const [employees,setEmployees]=useState([]),[rows,setRows]=useState([]),[employeeId,setEmployeeId]=useState(""),[form,setForm]=useState({feedback_type:"Desenvolvimento",context:"",strengths:"",development_points:"",action_plan:"",comment:""}),[open,setOpen]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState("");
 const role=profile?.access_role||"employee", employee=employees.find(e=>e.id===employeeId);
 async function load(){if(!company?.id)return;setLoading(true);setError("");let q=supabase.from("employees").select("id,full_name,role,manager_id,profile_id").eq("status","ativo").order("full_name");if(role==="employee")q=q.eq("profile_id",profile.id);if(role==="gestor")q=q.eq("manager_id",profile.id);const {data:es,error:e1}=await q;const {data:fs,error:e2}=await supabase.from("hr_feedbacks").select("id,employee_id,feedback_type,context,strengths,development_points,action_plan,comment,feedback_date,status,created_at").eq("company_id",company.id).order("feedback_date",{ascending:false});if(e1||e2)setError((e1||e2).message);else{setEmployees(es||[]);setRows(fs||[]);if(!employeeId&&es?.[0])setEmployeeId(es[0].id)}setLoading(false)}
 useEffect(()=>{load()},[company?.id,profile?.id,role]);
 async function save(e){e.preventDefault();if(!employeeId)return;setError("");const {error}=await supabase.from("hr_feedbacks").insert({...form,company_id:company.id,employee_id:employeeId,author_profile_id:profile.id,status:"registrado"});if(error)setError(error.message);else{setForm({feedback_type:"Desenvolvimento",context:"",strengths:"",development_points:"",action_plan:"",comment:""});setOpen(false);load()}}
 const mine=rows.filter(r=>r.employee_id===employeeId);
 return <div><header style={s.header}><div><div style={s.kicker}>Gestão de Pessoas</div><h1 style={s.title}>Feedbacks</h1><p style={s.sub}>Registre, acompanhe e documente conversas de desenvolvimento.</p></div><div className="no-print" style={{display:"flex",gap:8}}><button style={s.btnGhost} onClick={()=>window.print()}>🖨 Imprimir</button>{role!=="employee"&&<button style={s.btn} onClick={()=>setOpen(!open)}>{open?"Cancelar":"+ Novo feedback"}</button>}</div></header>
 <div className="no-print" style={s.selector}><label>Colaborador<select value={employeeId} onChange={e=>setEmployeeId(e.target.value)} disabled={role==="employee"} style={s.input}>{employees.map(e=><option key={e.id} value={e.id}>{e.full_name} — {e.role||"Sem cargo"}</option>)}</select></label></div>
 {error&&<div style={s.error}>{error}</div>}{open&&<form className="no-print" onSubmit={save} style={s.form}><label>Tipo<select style={s.input} value={form.feedback_type} onChange={e=>setForm({...form,feedback_type:e.target.value})}>{TYPES.map(x=><option key={x}>{x}</option>)}</select></label>{[["context","Contexto"],["strengths","Pontos positivos"],["development_points","Pontos de desenvolvimento"],["action_plan","Plano de ação"],["comment","Comentário geral"]].map(([k,l])=><label key={k}>{l}<textarea style={{...s.input,minHeight:75}} value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/></label>)}<button style={s.btn} type="submit">Registrar feedback</button></form>}
 <section style={s.card}><div style={s.cardHead}><h2>{employee?employee.full_name:"Feedbacks"}</h2><span>{mine.length} registro(s)</span></div>{loading?<p style={s.dim}>Carregando...</p>:mine.length===0?<p style={s.dim}>Nenhum feedback registrado para este colaborador.</p>:mine.map(r=><article key={r.id} style={s.item}><div style={s.itemTop}><strong>{r.feedback_type}</strong><span>{new Date(r.feedback_date).toLocaleDateString("pt-BR")}</span></div>{r.context&&<p><b>Contexto:</b> {r.context}</p>}{r.strengths&&<p><b>Pontos positivos:</b> {r.strengths}</p>}{r.development_points&&<p><b>Desenvolvimento:</b> {r.development_points}</p>}{r.action_plan&&<p><b>Plano de ação:</b> {r.action_plan}</p>}{r.comment&&<p><b>Comentário:</b> {r.comment}</p>}</article>)}</section>
 <div className="print-only" style={{marginTop:30,fontSize:11}}>Documento gerado pelo ProdPersonal • {new Date().toLocaleString("pt-BR")}</div></div>
}
const s={header:{display:"flex",justifyContent:"space-between",alignItems:"end",gap:16,marginBottom:18},kicker:{fontSize:11,fontWeight:800,textTransform:"uppercase",letterSpacing:'.08em',color:'var(--amber)'},title:{fontFamily:'var(--font-display)',fontSize:24,margin:0},sub:{color:'var(--text-dim)',fontSize:13,margin:'6px 0 0'},btn:{background:'var(--amber)',color:'#fff',border:0,borderRadius:'var(--radius)',padding:'9px 14px',fontWeight:700,cursor:'pointer'},btnGhost:{background:'var(--panel)',color:'var(--text)',border:'1px solid var(--line)',borderRadius:'var(--radius)',padding:'9px 14px',fontWeight:700,cursor:'pointer'},selector:{background:'var(--panel)',border:'1px solid var(--line)',borderRadius:'var(--radius)',padding:16,marginBottom:16},input:{display:'block',width:'100%',marginTop:6,background:'var(--panel-2)',border:'1px solid var(--line)',borderRadius:'var(--radius)',padding:'9px',color:'var(--text)'},form:{display:'grid',gap:12,background:'var(--panel)',border:'1px solid var(--line)',borderRadius:'var(--radius)',padding:18,marginBottom:16},card:{background:'var(--panel)',border:'1px solid var(--line)',borderRadius:'var(--radius)',padding:18},cardHead:{display:'flex',justifyContent:'space-between',alignItems:'center',borderBottom:'1px solid var(--line)',paddingBottom:12,marginBottom:12},item:{borderBottom:'1px solid var(--line)',padding:'14px 0'},itemTop:{display:'flex',justifyContent:'space-between',marginBottom:8},dim:{color:'var(--text-dim)'},error:{padding:10,marginBottom:12,color:'var(--red)',border:'1px solid var(--red)',borderRadius:'var(--radius)'}}