import { useEffect,useState } from "react";
import ModulePage from "../components/ModulePage";
import { supabase } from "../lib/supabaseClient";
import { useAuth } from "../lib/AuthContext";

export default function MetasPage(){
 const {company,profile}=useAuth(); const role=profile?.access_role||"employee"; const canManage=["rh","dp","admin","master"].includes(role);
 const [options,setOptions]=useState([]),[rows,setRows]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState("");
 useEffect(()=>{if(!company?.id||!profile?.id)return;async function load(){setLoading(true);let q=supabase.from("employees").select("id,full_name,profile_id,manager_id").eq("company_id",company.id).eq("status","ativo").order("full_name");if(role==="gestor")q=q.eq("manager_id",profile.id);if(role==="employee")q=q.eq("profile_id",profile.id);const {data,error}=await q;if(error)setError(error.message);else setOptions((data||[]).map(e=>({value:e.id,label:e.full_name})));setLoading(false)}load()},[company?.id,profile?.id,role]);
 useEffect(()=>{if(!company?.id||canManage||!options.length)return;async function load(){const ids=options.map(x=>x.value);const {data,error}=await supabase.from("hr_goals").select("id,description,target_value,current_value,due_date,status,employee_id").eq("company_id",company.id).in("employee_id",ids).order("due_date",{ascending:true});if(error)setError(error.message);else setRows(data||[])}load()},[company?.id,canManage,options]);
 if(canManage)return <ModulePage table="hr_goals" title="Metas e KPIs" subtitle="Metas individuais alinhadas com a estratégia da empresa." emptyLabel="Nenhuma meta cadastrada ainda." fields={[{key:"employee_id",label:"Colaborador",type:"select",options,required:true},{key:"description",label:"Descrição da meta",placeholder:"Ex: Reduzir tempo médio de atendimento",required:true},{key:"target_value",label:"Valor alvo",type:"number"},{key:"current_value",label:"Valor atual",type:"number"},{key:"due_date",label:"Prazo",type:"date"},{key:"status",label:"Status",type:"select",options:[{value:"em_andamento",label:"Em andamento"},{value:"atingida",label:"Atingida"},{value:"nao_atingida",label:"Não atingida"}]}]}/>;
 return <div><header style={s.header}><h1 style={s.title}>Minhas Metas e KPIs</h1><p style={s.sub}>Acompanhe seus objetivos e resultados.</p></header>{error&&<div style={s.error}>{error}</div>}{loading?<p style={s.dim}>Carregando...</p>:rows.length===0?<p style={s.dim}>Nenhuma meta registrada.</p>:<div style={s.list}>{rows.map(x=>{const target=Number(x.target_value),current=Number(x.current_value),pct=target?Math.max(0,Math.min(100,current/target*100)):0;return <article key={x.id} style={s.card}><div style={s.head}><strong>{x.description}</strong><b>{pct.toFixed(0)}%</b></div><div style={s.track}><div style={{...s.fill,width:`${pct}%`}}/></div><p><b>Atual:</b> {x.current_value??"—"} · <b>Alvo:</b> {x.target_value??"—"}</p><p><b>Prazo:</b> {x.due_date?new Date(x.due_date+"T00:00:00").toLocaleDateString("pt-BR"):"—"} · <b>Status:</b> {x.status||"—"}</p></article>})}</div>}</div>;
}
const s={header:{marginBottom:20},title:{fontFamily:"var(--font-display)",fontSize:22,margin:0},sub:{color:"var(--text-dim)",fontSize:13,margin:"6px 0 0"},list:{display:"grid",gap:12,maxWidth:900},card:{background:"var(--panel)",border:"1px solid var(--line)",borderRadius:"var(--radius)",padding:18},head:{display:"flex",justifyContent:"space-between",gap:12},track:{height:8,background:"var(--panel-2)",borderRadius:4,overflow:"hidden",margin:"12px 0"},fill:{height:"100%",background:"var(--amber)"},dim:{color:"var(--text-dim)"},error:{padding:10,color:"var(--red)",border:"1px solid var(--red)",borderRadius:"var(--radius)"}};