import { useEffect,useState } from "react";
import { supabase } from "../lib/supabaseClient";
import { useAuth } from "../lib/AuthContext";
const STATUS_LABEL={nova:"Nova",em_analise:"Em análise",implementada:"Implementada",recusada:"Recusada"};
const STATUS_COLOR={nova:"var(--text-dim)",em_analise:"var(--amber)",implementada:"var(--green)",recusada:"var(--red)"};
const ADMIN_ROLES=["rh","dp","hr","admin","administrator","master"];
const MANAGER_ROLES=["gestor","manager","supervisor","coordinator","coordenador","gerente","leader","lider"];
export default function SugestoesPage(){
 const {company,profile}=useAuth();const role=String(profile?.access_role||profile?.role||"employee").toLowerCase();const isEmployee=role==="employee";const isReadOnly=!isEmployee;
 const [employees,setEmployees]=useState([]),[suggestions,setSuggestions]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[employeeId,setEmployeeId]=useState(""),[title,setTitle]=useState(""),[description,setDescription]=useState(""),[saving,setSaving]=useState(false);
 async function loadAll(){if(!company?.id||!profile?.id)return;setLoading(true);setError("");try{let eq=supabase.from("employees").select("id,full_name,profile_id,manager_id").eq("company_id",company.id).eq("status","ativo").order("full_name");if(isEmployee)eq=eq.eq("profile_id",profile.id);else if(MANAGER_ROLES.includes(role)){const me=await supabase.from("employees").select("id").eq("profile_id",profile.id).maybeSingle();if(me.error)throw me.error;if(me.data)eq=eq.eq("manager_id",me.data.id);}const {data:emp,error:e1}=await eq;let sq=supabase.from("hr_suggestions").select("id,title,description,status,created_at,employee_id,employees:employee_id(full_name)").eq("company_id",company.id).order("created_at",{ascending:false});if(isEmployee&&emp?.[0])sq=sq.eq("employee_id",emp[0].id);else if(MANAGER_ROLES.includes(role)&&emp?.length)sq=sq.in("employee_id",emp.map(x=>x.id));const {data:sg,error:e2}=await sq;if(e1||e2)throw e1||e2;setEmployees(emp||[]);setSuggestions(sg||[]);if(isEmployee&&emp?.[0])setEmployeeId(emp[0].id)}catch(err){setError("Não foi possível carregar: "+(err.message||"erro desconhecido"));}finally{setLoading(false)}}
 useEffect(()=>{loadAll()},[company?.id,profile?.id,role]);
 async function submit(e){e.preventDefault();if(!isEmployee)return;if(!title)return setError("Dê um título à sugestão.");if(!employeeId)return setError("Não foi possível identificar o colaborador.");setSaving(true);setError("");const {error}=await supabase.from("hr_suggestions").insert({company_id:company.id,employee_id:employeeId,title,description:description||null});if(error)setError(error.message);else{setTitle("");setDescription("");await loadAll()}setSaving(false)}
 return <div><header style={{marginBottom:20}}><h1 style={s.title}>Caixa de Sugestões</h1><p style={s.subtitle}>{isEmployee?"Registre uma ideia e acompanhe o retorno da empresa.":"Consulte as sugestões registradas e acompanhe seus status."}</p></header>{error&&<div style={s.error}>{error}</div>}{isEmployee&&<form onSubmit={submit} style={s.form}><p style={s.formTitle}>Nova sugestão</p><div style={s.identity}><span>Colaborador</span><strong>{employees[0]?.full_name||"Carregando..."}</strong></div><input style={s.input} placeholder="Título da sugestão" value={title} onChange={e=>setTitle(e.target.value)} required/><textarea style={{...s.input,minHeight:100,resize:"vertical"}} placeholder="Descreva sua ideia, melhoria ou oportunidade..." value={description} onChange={e=>setDescription(e.target.value)}/><button style={s.saveBtn} type="submit" disabled={saving}>{saving?"Enviando...":"Enviar sugestão"}</button></form>}{isReadOnly&&<div style={s.readOnly}><strong>Modo consulta</strong><span>Gestores e RH/DP podem visualizar as sugestões, mas não registram novas sugestões nesta tela.</span></div>}<h2 style={s.title2}>{isEmployee?"Minhas sugestões":"Sugestões recebidas"}</h2>{loading?<p style={s.dim}>Carregando...</p>:suggestions.length===0?<p style={s.dim}>{isEmployee?"Você ainda não registrou sugestões.":"Nenhuma sugestão encontrada para sua área de acesso."}</p>:<div style={s.list}>{suggestions.map(x=><div key={x.id} style={s.card}><div style={s.cardHeader}><div><strong>{x.title}</strong><p style={s.dim}>{x.employees?.full_name||"Anônima"} · {new Date(x.created_at).toLocaleDateString("pt-BR")}</p></div><span style={{...s.badge,color:STATUS_COLOR[x.status]||"var(--text)"}}>{STATUS_LABEL[x.status]||x.status||"Registrada"}</span></div>{x.description&&<p style={s.description}>{x.description}</p>}</div>)}</div>}</div>;
}
const s={title:{fontFamily:"var(--font-display)",fontSize:22,margin:0},title2:{fontFamily:"var(--font-display)",fontSize:16,margin:"24px 0 12px"},subtitle:{color:"var(--text-dim)",fontSize:13,margin:"6px 0 0"},dim:{color:"var(--text-dim)",fontSize:12.5},form:{display:"flex",flexDirection:"column",gap:12,background:"var(--panel)",border:"1px solid var(--line)",borderRadius:"var(--radius)",padding:20,marginBottom:20,maxWidth:700},formTitle:{fontSize:13,fontWeight:700,color:"var(--text-dim)",textTransform:"uppercase",letterSpacing:".04em",margin:0},identity:{display:"flex",flexDirection:"column",gap:4,background:"var(--panel-2)",border:"1px solid var(--line)",borderRadius:"var(--radius)",padding:"10px 12px"},input:{background:"var(--panel-2)",border:"1px solid var(--line)",borderRadius:"var(--radius)",padding:"10px 11px",color:"var(--text)",fontSize:13,fontFamily:"inherit"},saveBtn:{background:"var(--amber)",color:"#fff",border:0,borderRadius:"var(--radius)",padding:"10px 0",fontWeight:700,cursor:"pointer"},readOnly:{display:"flex",flexDirection:"column",gap:4,background:"var(--panel-2)",border:"1px solid var(--line)",borderRadius:"var(--radius)",padding:"12px 14px",maxWidth:700,fontSize:13},list:{display:"flex",flexDirection:"column",gap:12,maxWidth:900},card:{background:"var(--panel)",border:"1px solid var(--line)",borderRadius:"var(--radius)",padding:16},cardHeader:{display:"flex",justifyContent:"space-between",alignItems:"flex-start",gap:12},badge:{fontSize:11,fontWeight:800,padding:"4px 8px",border:"1px solid var(--line)",borderRadius:999,whiteSpace:"nowrap"},description:{fontSize:13,lineHeight:1.6,whiteSpace:"pre-line"},error:{background:"rgba(217,105,95,.12)",border:"1px solid var(--red)",color:"var(--red)",borderRadius:"var(--radius)",padding:10,fontSize:13,marginBottom:16}};
