import { useEffect,useState } from "react";
import { supabase } from "../lib/supabaseClient";
import { useAuth } from "../lib/AuthContext";
const STATUS_LABEL={nova:"Nova",em_analise:"Em análise",implementada:"Implementada",recusada:"Recusada"};
const STATUS_COLOR={nova:"var(--text-dim)",em_analise:"var(--amber)",implementada:"var(--green)",recusada:"var(--red)"};
export default function SugestoesPage(){
 const {company,profile}=useAuth();const role=profile?.access_role||"employee",isEmployee=role==="employee";
 const [employees,setEmployees]=useState([]),[suggestions,setSuggestions]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[employeeId,setEmployeeId]=useState(""),[title,setTitle]=useState(""),[description,setDescription]=useState(""),[saving,setSaving]=useState(false);
 async function loadAll(){if(!company?.id||!profile?.id)return;setLoading(true);try{let eq=supabase.from("employees").select("id,full_name,profile_id,manager_id").eq("company_id",company.id).eq("status","ativo").order("full_name");if(isEmployee)eq=eq.eq("profile_id",profile.id);if(role==="gestor")eq=eq.eq("manager_id",profile.id);const {data:emp,error:e1}=await eq;let sq=supabase.from("hr_suggestions").select("id,title,description,status,created_at,employee_id,employees:employee_id(full_name)").eq("company_id",company.id).order("created_at",{ascending:false});if(isEmployee&&emp?.[0])sq=sq.eq("employee_id",emp[0].id);const {data:sg,error:e2}=await sq;if(e1||e2)throw e1||e2;setEmployees(emp||[]);setSuggestions(sg||[]);if(isEmployee&&emp?.[0])setEmployeeId(emp[0].id);else if(!employeeId&&emp?.[0])setEmployeeId(emp[0].id);}catch(err){setError("Não foi possível carregar: "+(err.message||"erro desconhecido"));}finally{setLoading(false)}}
 useEffect(()=>{loadAll()},[company?.id,profile?.id,role]);
 async function submit(e){e.preventDefault();if(!title)return setError("Dê um título à sugestão.");if(!employeeId&&role!=="rh"&&role!=="dp"&&role!=="admin"&&role!=="master")return setError("Não foi possível identificar o colaborador.");setSaving(true);setError("");const {error}=await supabase.from("hr_suggestions").insert({company_id:company.id,employee_id:employeeId||null,title,description:description||null});if(error)setError(error.message);else{setEmployeeId(isEmployee?employeeId:"");setTitle("");setDescription("");await loadAll()}setSaving(false)}
 async function updateStatus(id,status){await supabase.from("hr_suggestions").update({status}).eq("id",id);await loadAll()}
 return <div><header style={{marginBottom:20}}><h1 style={s.title}>Caixa de Sugestões</h1><p style={s.subtitle}>Registre ideias e acompanhe o tratamento das sugestões.</p></header>{error&&<div style={s.error}>{error}</div>}<form onSubmit={submit} style={s.form}><p style={s.formTitle}>Nova sugestão</p>{isEmployee?<div style={s.identity}><span>Colaborador</span><strong>{employees[0]?.full_name||"Carregando..."}</strong></div>:<select style={s.input} value={employeeId} onChange={e=>setEmployeeId(e.target.value)}><option value="">Selecione o colaborador...</option>{employees.map(e=><option key={e.id} value={e.id}>{e.full_name}</option>)}</select>}<input style={s.input} placeholder="Título da sugestão" value={title} onChange={e=>setTitle(e.target.value)} required/><textarea style={{...s.input,minHeight:80}} placeholder="Descrição (opcional)" value={description} onChange={e=>setDescription(e.target.value)}/><button style={s.saveBtn} type="submit" disabled={saving}>{saving?"Enviando...":"Enviar sugestão"}</button></form><h2 style={s.title2}>{isEmployee?"Minhas sugestões":"Sugestões recebidas"}</h2>{loading?<p style={s.dim}>Carregando...</p>:suggestions.length===0?<p style={s.dim}>{isEmployee?"Você ainda não registrou sugestões.":"Nenhuma sugestão ainda."}</p>:<div style={s.list}>{suggestions.map(x=><div key={x.id} style={s.card}><div style={s.cardHeader}><strong>{x.title}</strong>{!isEmployee?<select style={{...s.select,color:STATUS_COLOR[x.status]}} value={x.status} onChange={e=>updateStatus(x.id,e.target.value)}>{Object.entries(STATUS_LABEL).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select>:<span style={{color:STATUS_COLOR[x.status],fontWeight:700,fontSize:12}}>{STATUS_LABEL[x.status]}</span>}</div>{!isEmployee&&<p style={s.dim}>{x.employees?.full_name||"Anônima"} · {new Date(x.created_at).toLocaleDateString("pt-BR")}</p>}{x.description&&<p>{x.description}</p>}</div>)}</div>}</div>;
}
const s={title:{fontFamily:"var(--font-display)",fontSize:22,margin:0},title2:{fontFamily:"var(--font-display)",fontSize:16,margin:"24px 0 12px"},subtitle:{color:"var(--text-dim)",fontSize:13,margin:"6px 0 0"},dim:{color:"var(--text-dim)",fontSize:12.5},form:{display:"flex",flexDirection:"column",gap:12,background:"var(--panel)",border:"1px solid var(--line)",borderRadius:"var(--radius)",padding:20,marginBottom:28,maxWidth:680},formTitle:{fontSize:13,fontWeight:700,color:"var(--text-dim)",textTransform:"uppercase",letterSpacing:".04em",margin:0},identity:{display:"flex",flexDirection:"column",gap:4,background:"var(--panel-2)",border:"1px solid var(--line)",borderRadius:"var(--radius)",padding:"9px 10px"},input:{background:"var(--panel-2)",border:"1px solid var(--line)",borderRadius:"var(--radius)",padding:"9px 10px",color:"var(--text)",fontSize:13,fontFamily:"inherit"},saveBtn:{background:"var(--amber)",color:"#fff",border:0,borderRadius:"var(--radius)",padding:"10px 0",fontWeight:700,cursor:"pointer"},list:{display:"flex",flexDirection:"column",gap:12,maxWidth:800},card:{background:"var(--panel)",border:"1px solid var(--line)",borderRadius:"var(--radius)",padding:16},cardHeader:{display:"flex",justifyContent:"space-between",alignItems:"center",gap:12},select:{background:"var(--panel-2)",border:"1px solid var(--line)",borderRadius:"var(--radius)",padding:"4px 8px",fontSize:11.5,fontWeight:700},error:{background:"rgba(217,105,95,.12)",border:"1px solid var(--red)",color:"var(--red)",borderRadius:"var(--radius)",padding:10,fontSize:13,marginBottom:16}};