import { NavLink, useNavigate, useLocation } from "react-router-dom";
import { useEffect, useState } from "react";
import { useAuth } from "../lib/AuthContext";
import { supabase } from "../lib/supabaseClient";

const ADMIN_NAV = [
  {to:"/dashboard",label:"Dashboard",icon:"📊"},{to:"/colaboradores",label:"Colaboradores",icon:"👤"},{to:"/central-avaliacoes",label:"Central de Avaliações",icon:"★"},{to:"/feedbacks",label:"Feedbacks",icon:"💬"},{to:"/comunicados",label:"Comunicados e Documentos",icon:"📢"},{to:"/descricao-cargos",label:"Descrição de Cargos",icon:"📄"},{to:"/treinamentos",label:"Treinamentos",icon:"🎓"},{to:"/carreira",label:"Plano de Carreira",icon:"🪜"},{to:"/sucessao",label:"Plano de Sucessão",icon:"👥"},{to:"/vagas",label:"Recrutamento",icon:"📋"},{to:"/mural",label:"Mural",icon:"📌"},{to:"/clima",label:"Clima Organizacional",icon:"😊"},{to:"/denuncias",label:"Canal de Denúncias",icon:"⚠️"},{to:"/sugestoes",label:"Sugestões",icon:"💡"},{to:"/remuneracao",label:"Remuneração",icon:"💵"},{to:"/ferias",label:"Controle de Férias",icon:"🏖️"},{to:"/assinatura",label:"Assinatura",icon:"◈"}
];
const EMPLOYEE_NAV = [
  {to:"/dashboard",label:"Meu Portal",icon:"🏠"},{to:"/central-avaliacoes",label:"Minhas Avaliações",icon:"★"},{to:"/feedbacks",label:"Meus Feedbacks",icon:"💬"},{to:"/comunicados",label:"Minha Caixa de Entrada",icon:"📥"},{to:"/pdi",label:"Meu PDI",icon:"🎯"},{to:"/metas",label:"Minhas Metas",icon:"📈"},{to:"/carreira",label:"Minha Carreira",icon:"🪜"},{to:"/sugestoes",label:"Sugestões",icon:"💡"},{to:"/clima",label:"Meu Clima",icon:"😊"}
];
const MANAGER_NAV = [...ADMIN_NAV.filter(x=>!["/remuneracao","/colaboradores","/denuncias"].includes(x.to)),{to:"/colaboradores",label:"Minha Equipe",icon:"👥"}];
function navFor(role){if(role==="employee")return EMPLOYEE_NAV;if(role==="gestor")return MANAGER_NAV;return ADMIN_NAV;}
function removeDuplicateEmployeeName(root,fullName){if(!root||!fullName)return;const n=String(fullName).trim().toLocaleLowerCase("pt-BR");if(!n)return;root.querySelectorAll("h1,h2,h3,h4,h5,h6,strong,span,p,div").forEach(el=>{if(el.closest(".employeeIdentity")||el.closest("select")||el.closest("option"))return;const t=(el.textContent||"").trim().toLocaleLowerCase("pt-BR");if(t===n||t.startsWith("olá,")&&t.includes(n.split(/\s+/)[0]))el.style.display="none";});}
function EmployeeMuralPreview({company}){
 const [posts,setPosts]=useState([]);
 useEffect(()=>{if(!company?.id)return;let active=true;(async()=>{const {data}=await supabase.from("hr_mural_posts").select("id,title,content,pinned,created_at").eq("company_id",company.id).order("pinned",{ascending:false}).order("created_at",{ascending:false}).limit(5);if(active)setPosts(data||[]);})();return()=>{active=false}},[company?.id]);
 if(!posts.length)return null;
 return <section style={styles.muralPreview}><div style={styles.muralHead}><div><span style={styles.muralEyebrow}>Comunicação interna</span><h2 style={styles.muralTitle}>📌 Mural da empresa</h2></div><span style={styles.muralBadge}>{posts.length} aviso(s)</span></div>{posts.map(p=><article key={p.id} style={styles.muralPost}><div><strong>{p.pinned&&"📌 "}{p.title}</strong>{p.content&&<p style={styles.muralText}>{p.content}</p>}<small style={styles.muralDate}>{new Date(p.created_at).toLocaleDateString("pt-BR")}</small></div></article>)}</section>;
}
export default function Layout({children}){
 const {profile,company,signOut}=useAuth();const navigate=useNavigate(),location=useLocation();const role=profile?.access_role||"employee",isEmployee=role==="employee",showEmployeeMural=isEmployee&&location.pathname==="/dashboard";
 useEffect(()=>{if(!isEmployee||!profile?.full_name)return;const timer=setTimeout(()=>removeDuplicateEmployeeName(document.querySelector(".app-main"),profile.full_name),0);return()=>clearTimeout(timer)},[isEmployee,profile?.full_name,location.pathname]);
 async function handleSignOut(){await signOut();navigate("/login");}
 const nav=navFor(role);
 const roleLabel=isEmployee?"Portal do Colaborador":role==="gestor"?"Gestão de Equipe":role==="dp"?"Departamento Pessoal":role==="rh"?"Recursos Humanos":"Administração";
 return <div style={styles.wrap}><aside className="no-print" style={styles.sidebar}><div style={styles.brandWrap}><img src="/brand/prodpersonal-logo.svg" alt="ProdPersonal" style={styles.logo}/></div><div style={styles.roleBadge}>{roleLabel}</div><nav style={styles.nav}>{nav.map(item=><NavLink key={item.to} to={item.to} style={({isActive})=>({...styles.navItem,...(isActive?styles.navItemActive:{})})}><span>{item.icon}</span>{item.label}</NavLink>)}</nav><div style={styles.footer}>{!isEmployee&&<div style={styles.userName}>{profile?.full_name??profile?.email}</div>}<button style={styles.signOutBtn} onClick={handleSignOut} type="button">Sair</button></div></aside><main className="app-main" style={styles.main}>{isEmployee&&<div className="no-print employeeIdentity" style={styles.employeeIdentity}><span style={styles.identityDot}>●</span><strong>{profile?.full_name??profile?.email}</strong><span style={styles.identityLabel}>Portal pessoal</span></div>}{showEmployeeMural&&<EmployeeMuralPreview company={company}/>} {children}</main></div>;
}
const styles={wrap:{display:"flex",minHeight:"100vh",background:"var(--bg)"},sidebar:{width:230,background:"var(--panel)",borderRight:"1px solid var(--line)",display:"flex",flexDirection:"column",padding:"16px 12px",flexShrink:0},brandWrap:{padding:"0 5px 10px"},logo:{width:"100%",height:58,objectFit:"contain",objectPosition:"left center",display:"block",borderRadius:10},roleBadge:{margin:"0 8px 14px",padding:"6px 8px",border:"1px solid var(--line)",borderRadius:"var(--radius)",fontSize:10.5,fontWeight:800,color:"var(--text-dim)",textTransform:"uppercase",letterSpacing:".04em"},nav:{display:"flex",flexDirection:"column",gap:2,flex:1,overflowY:"auto"},navItem:{display:"flex",alignItems:"center",gap:10,padding:"9px 10px",borderRadius:"var(--radius)",color:"var(--text-dim)",fontSize:13,fontWeight:600,textDecoration:"none"},navItemActive:{background:"var(--panel-2)",color:"var(--text)"},footer:{borderTop:"1px solid var(--line)",paddingTop:14,marginTop:14},userName:{fontSize:12.5,color:"var(--text-dim)",marginBottom:8,padding:"0 8px"},signOutBtn:{width:"100%",background:"transparent",border:"1px solid var(--line)",borderRadius:"var(--radius)",padding:"8px 0",color:"var(--text-dim)",fontSize:12.5,fontWeight:600,cursor:"pointer"},main:{flex:1,padding:28,overflowY:"auto"},employeeIdentity:{display:"flex",alignItems:"center",gap:8,margin:"-8px 0 22px",paddingBottom:12,borderBottom:"1px solid var(--line)",fontSize:13},identityDot:{color:"var(--green)",fontSize:9},identityLabel:{color:"var(--text-dim)",fontSize:11.5},muralPreview:{background:"var(--panel)",border:"1px solid var(--line)",borderRadius:"var(--radius)",padding:18,marginBottom:20},muralHead:{display:"flex",justifyContent:"space-between",alignItems:"center",gap:12,marginBottom:12},muralEyebrow:{display:"block",color:"var(--amber)",fontSize:10,fontWeight:800,textTransform:"uppercase",letterSpacing:".08em"},muralTitle:{fontFamily:"var(--font-display)",fontSize:19,margin:"3px 0 0"},muralBadge:{fontSize:11,color:"var(--text-dim)",border:"1px solid var(--line)",borderRadius:999,padding:"5px 9px"},muralPost:{padding:"12px 0",borderTop:"1px solid var(--line)"},muralText:{color:"var(--text-dim)",fontSize:13,margin:"5px 0"},muralDate:{color:"var(--text-dim)",fontSize:10}};
